### ISSUE TITLE
Cross-platform

### ISSUE THREAD

**Issue by Abe404** [noble-research-institute/RhizoVisionExplorer#1]
Thanks for the awesome software.

Any thoughts on support for Mac (OSX) or Linux?

Thanks!

**Comment by lmyork** [comment]
Hi Abe. Thanks for trying out RhizoVision Explorer. We would definitely like to support as many users as possible, and focused on Windows to have the maximum impact with the initial release. We've heard of success from other users running on both OSX and Linux using Windows emulators, but we can't provide much technical assistance in that regard. The software is written using cross-platform packages like OpenCV and QT so it should be possible to compile to provide native support for at least Linux in addition. We will try our best to do this when releasing the next version, if not earlier. We would love having community support for tackling issues like this, and you are of course welcome to help out. Thanks!

**Comment by Abe404** [comment]
Hi Larry, 

Thanks for the detailed response. I think that makes sense.
